#!/bin/sh

# Prevent pushing to branches "main", "master" & "develop"

while read local_ref local_oid remote_ref remote_oid
do
    case "$remote_ref" in
    *"main"*|*"master"*|*"develop"*)
        echo "Cannot push to the $remote_ref branch"
        exit 1
    ;;
    esac
done
